[build]
rustflags = ["-C", "target-cpu=native", "-Z", "share-generics=y", "-C", "target-feature=+avx,+avx2,+fma"]
linker = "rust-lld"


[profile.release]
panic = "abort"
codegen-units = 1
lto = "fat"
debug = 1


# [profile.bench]
# panic = "abort"
# codegen-units = 1
# lto = "thin"